#!/usr/bin/env python3
"""Calculate the bounded 1.0 resource acceptance record from native evidence."""
import hashlib,json,pathlib
R=pathlib.Path(__file__).resolve().parents[1]
def calculate(root=R):
    load=lambda p:json.loads((root/p).read_text())
    corpus=load('corpus/disc.json');review=load('reviews/transcription-review-v1.json');anchors=load('spatial/group-anchors.json');claims=load('apparatus/claims.json');report=load('research/family-readiness-v1.json')
    paths=['corpus/disc.json','data/evans1909-groups.csv','reviews/transcription-review-v1.json','apparatus/claims.json','apparatus/stroke-assertions.json','spatial/group-anchors.json','analysis/descriptive-v1.json','exports/aegean-interop.json','research/family-readiness-v1.json','workbench/index.html']
    criteria={'source_and_transcription_identity_pinned':bool(review['input_sha256'] and review['source_sha256']),'all_native_group_labels_reviewed':len(set(review['checked_groups']))==61,'source_attributed_slot_coverage':len(corpus['occurrences'])==242,'unknown_slot_preserved':sum(o['sign_id'] is None for o in corpus['occurrences'])==1,'source_disagreements_preserved':len(claims)==7,'source_figure_navigation_coverage':len(anchors)==61 and all(a['approximate'] for a in anchors),'descriptive_and_export_checks_present':all((root/'scripts'/p).is_file() for p in ['test_analysis.py','test_exports.py','test_release.py']),'offline_workbench_present':(root/'workbench/index.html').is_file(),'family_claim_boundary_preserved':report['pooled_analysis_allowed'] is False and report['linguistic_known_answer_control']['state']=='BLOCKED','stronger_claims_not_promoted':review['external_peer_review_completed'] is False and all(o['phonetic_value'] is None for o in corpus['occurrences'])}
    return {'release_version':(root/'VERSION').read_text().strip(),'acceptance_scope':'Stable source-attributed project research edition and software; not an externally certified critical reading or decipherment.','status':'PASS' if all(criteria.values()) else 'FAIL','criteria':criteria,'evidence':[{'path':p,'sha256':hashlib.sha256((root/p).read_bytes()).hexdigest()} for p in paths],'publication_gates':['Native/adversarial tests pass','Exact primary source bytes reacquired in CI','Desktop/mobile browser interaction tests pass in CI','Release archive generated only after all CI jobs succeed'],'remaining_evidence_gates':['External independent epigraphic review','Additional checked photographic witnesses','Complete source-checked stroke inventory and unresolved targets','Physical per-stamp coordinates','Legitimate linguistic known-answer control and compatible family target vectors','Independent linguistic evidence for decipherment'],'external_peer_review_completed':False,'physical_independent_documents':1}
if __name__=='__main__':print(json.dumps(calculate(),indent=2))
